import { Article, Product, Category } from './types';

export const categories: Category[] = [
  {
    id: '1', name: 'Dream Meanings', slug: 'dreams', description: 'Explore the symbolism behind your dreams',
    icon: '🌙', count: 248, color: '#6366F1', image: 'https://images.pexels.com/photos/1028741/pexels-photo-1028741.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: '2', name: 'Health & Wellness', slug: 'health', description: 'Evidence-based health guidance',
    icon: '❤️', count: 312, color: '#EF4444', image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: '3', name: 'Ayurveda', slug: 'ayurveda', description: 'Ancient wisdom for modern wellness',
    icon: '🌿', count: 195, color: '#10B981', image: 'https://images.pexels.com/photos/3735218/pexels-photo-3735218.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: '4', name: 'Yoga & Meditation', slug: 'yoga', description: 'Mind-body practices for balance',
    icon: '🧘', count: 167, color: '#F59E0B', image: 'https://images.pexels.com/photos/3823488/pexels-photo-3823488.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: '5', name: 'Beauty', slug: 'beauty', description: 'Natural beauty tips and remedies',
    icon: '💄', count: 221, color: '#EC4899', image: 'https://images.pexels.com/photos/3785147/pexels-photo-3785147.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: '6', name: 'Nutrition', slug: 'nutrition', description: 'Food as medicine, diet for life',
    icon: '🥗', count: 183, color: '#84CC16', image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: '7', name: 'Spirituality', slug: 'spirituality', description: 'Mantras, meditation, and wisdom',
    icon: '🙏', count: 142, color: '#8B5CF6', image: 'https://images.pexels.com/photos/1051838/pexels-photo-1051838.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: '8', name: 'Home Remedies', slug: 'home-remedies', description: 'Natural cures from your kitchen',
    icon: '🏠', count: 158, color: '#F97316', image: 'https://images.pexels.com/photos/1435904/pexels-photo-1435904.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
];

export const featuredArticles: Article[] = [
  {
    id: '1', slug: 'dream-about-cow-meaning',
    title: 'Dreaming of a Cow: Complete Spiritual & Cultural Meaning',
    excerpt: 'Cows in dreams are deeply symbolic in Hindu, Biblical, and Islamic traditions. Discover what it truly means when you dream about a cow.',
    category: 'Dream Meanings', subcategory: 'Animals',
    image: 'https://images.pexels.com/photos/735968/pexels-photo-735968.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Dr. Priya Sharma', authorImage: 'https://images.pexels.com/photos/3785079/pexels-photo-3785079.jpeg?auto=compress&cs=tinysrgb&w=100',
    date: 'July 4, 2026', readTime: 8, tags: ['cow', 'dream', 'spiritual', 'hinduism'],
    featured: true, trending: true, luckyNumber: 7, luckyColor: 'Green',
  },
  {
    id: '2', slug: 'ashwagandha-benefits-dosage',
    title: 'Ashwagandha: 12 Proven Benefits, Dosage & Side Effects',
    excerpt: 'Ashwagandha (Withania somnifera) is one of the most powerful herbs in Ayurvedic medicine. Modern research confirms many of its traditional uses.',
    category: 'Ayurveda', subcategory: 'Herbs',
    image: 'https://images.pexels.com/photos/6693663/pexels-photo-6693663.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Vaidya Rakesh Patel', authorImage: 'https://images.pexels.com/photos/3785081/pexels-photo-3785081.jpeg?auto=compress&cs=tinysrgb&w=100',
    date: 'July 3, 2026', readTime: 12, tags: ['ashwagandha', 'ayurveda', 'stress', 'adaptogen'],
    featured: true, trending: true,
  },
  {
    id: '3', slug: 'yoga-for-back-pain-beginners',
    title: '10 Best Yoga Poses for Back Pain Relief (With Instructions)',
    excerpt: 'Chronic back pain affects millions. These 10 evidence-backed yoga postures can provide lasting relief when practiced consistently.',
    category: 'Yoga & Meditation', subcategory: 'Yoga for Pain',
    image: 'https://images.pexels.com/photos/4056535/pexels-photo-4056535.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Ananya Krishnan', authorImage: 'https://images.pexels.com/photos/3785077/pexels-photo-3785077.jpeg?auto=compress&cs=tinysrgb&w=100',
    date: 'July 2, 2026', readTime: 10, tags: ['yoga', 'back pain', 'beginners', 'wellness'],
    featured: true, trending: false,
  },
  {
    id: '4', slug: 'remove-dark-circles-naturally',
    title: 'How to Remove Dark Circles Naturally: 15 Proven Home Remedies',
    excerpt: 'Dark circles under eyes can be caused by fatigue, genetics, or lifestyle. These natural remedies can help reduce them significantly.',
    category: 'Beauty', subcategory: 'Eye Care',
    image: 'https://images.pexels.com/photos/3762467/pexels-photo-3762467.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Meera Nair', authorImage: 'https://images.pexels.com/photos/3785077/pexels-photo-3785077.jpeg?auto=compress&cs=tinysrgb&w=100',
    date: 'July 1, 2026', readTime: 7, tags: ['dark circles', 'beauty', 'home remedies', 'eyes'],
    featured: false, trending: true,
  },
  {
    id: '5', slug: 'dream-about-snake-meaning',
    title: 'Dream About Snake: What Does It Really Mean?',
    excerpt: 'Snake dreams are among the most common and significant. Understand the symbolism across cultures and what your subconscious is telling you.',
    category: 'Dream Meanings', subcategory: 'Animals',
    image: 'https://images.pexels.com/photos/2062316/pexels-photo-2062316.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Dr. Priya Sharma', authorImage: 'https://images.pexels.com/photos/3785079/pexels-photo-3785079.jpeg?auto=compress&cs=tinysrgb&w=100',
    date: 'June 30, 2026', readTime: 9, tags: ['snake', 'dream', 'spiritual', 'subconscious'],
    featured: false, trending: true,
  },
  {
    id: '6', slug: 'giloy-benefits-immunity',
    title: 'Giloy (Guduchi): The Ultimate Immunity Booster Explained',
    excerpt: 'Giloy is called Amrita — the root of immortality in Sanskrit. Here\'s everything you need to know about this miraculous Ayurvedic herb.',
    category: 'Ayurveda', subcategory: 'Herbs',
    image: 'https://images.pexels.com/photos/3735218/pexels-photo-3735218.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Vaidya Rakesh Patel', authorImage: 'https://images.pexels.com/photos/3785081/pexels-photo-3785081.jpeg?auto=compress&cs=tinysrgb&w=100',
    date: 'June 29, 2026', readTime: 11, tags: ['giloy', 'immunity', 'ayurveda', 'herbs'],
    featured: false, trending: false,
  },
  {
    id: '7', slug: 'diabetes-diet-foods-to-eat-avoid',
    title: 'Diabetes Diet: 30 Best Foods to Eat and 10 to Avoid',
    excerpt: 'Managing diabetes through diet is powerful. This comprehensive guide covers glycemic index, portion control, and the best foods for blood sugar control.',
    category: 'Health & Wellness', subcategory: 'Diabetes',
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Dr. Suresh Mehta', authorImage: 'https://images.pexels.com/photos/3785081/pexels-photo-3785081.jpeg?auto=compress&cs=tinysrgb&w=100',
    date: 'June 28, 2026', readTime: 14, tags: ['diabetes', 'diet', 'blood sugar', 'health'],
    featured: false, trending: true,
  },
  {
    id: '8', slug: 'morning-yoga-routine-15-minutes',
    title: '15-Minute Morning Yoga Routine to Start Your Day Right',
    excerpt: 'A simple, effective morning yoga sequence that energizes the body, clears the mind, and sets a positive tone for the entire day.',
    category: 'Yoga & Meditation', subcategory: 'Morning Yoga',
    image: 'https://images.pexels.com/photos/3823488/pexels-photo-3823488.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Ananya Krishnan', authorImage: 'https://images.pexels.com/photos/3785077/pexels-photo-3785077.jpeg?auto=compress&cs=tinysrgb&w=100',
    date: 'June 27, 2026', readTime: 6, tags: ['yoga', 'morning', 'routine', 'beginners'],
    featured: false, trending: false,
  },
  {
    id: '9', slug: 'benefits-of-turmeric-milk',
    title: 'Golden Milk (Turmeric Latte): 8 Science-Backed Benefits',
    excerpt: 'Haldi doodh, or golden milk, has been used for centuries in Indian households. Modern science is now confirming its remarkable health benefits.',
    category: 'Nutrition', subcategory: 'Superfoods',
    image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Ritu Agarwal', authorImage: 'https://images.pexels.com/photos/3785079/pexels-photo-3785079.jpeg?auto=compress&cs=tinysrgb&w=100',
    date: 'June 26, 2026', readTime: 8, tags: ['turmeric', 'golden milk', 'nutrition', 'anti-inflammatory'],
    featured: false, trending: true,
  },
  {
    id: '10', slug: 'dream-about-water-meaning',
    title: 'Dreaming of Water: Spiritual Meaning Across Cultures',
    excerpt: 'Water in dreams can represent emotions, the subconscious, or spiritual cleansing. Learn the complete interpretation based on the water\'s condition.',
    category: 'Dream Meanings', subcategory: 'Elements',
    image: 'https://images.pexels.com/photos/1028741/pexels-photo-1028741.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Dr. Priya Sharma', authorImage: 'https://images.pexels.com/photos/3785079/pexels-photo-3785079.jpeg?auto=compress&cs=tinysrgb&w=100',
    date: 'June 25, 2026', readTime: 7, tags: ['water', 'dream', 'emotions', 'spiritual'],
    featured: false, trending: true,
  },
  {
    id: '11', slug: 'home-remedies-for-cold-cough',
    title: '12 Effective Home Remedies for Cold and Cough',
    excerpt: 'Before reaching for medicine, try these time-tested home remedies that can provide significant relief from cold and cough symptoms naturally.',
    category: 'Home Remedies', subcategory: 'Cold & Cough',
    image: 'https://images.pexels.com/photos/1435904/pexels-photo-1435904.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Dr. Anjali Desai', authorImage: 'https://images.pexels.com/photos/3785079/pexels-photo-3785079.jpeg?auto=compress&cs=tinysrgb&w=100',
    date: 'June 24, 2026', readTime: 9, tags: ['cold', 'cough', 'home remedies', 'natural'],
    featured: false, trending: false,
  },
  {
    id: '12', slug: 'om-mantra-benefits-chanting',
    title: 'The Power of OM: Benefits of Chanting & How to Practice',
    excerpt: 'OM is the most sacred sound in Vedic tradition. Modern neuroscience is discovering why chanting it has profound effects on the mind and body.',
    category: 'Spirituality', subcategory: 'Mantras',
    image: 'https://images.pexels.com/photos/1051838/pexels-photo-1051838.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Swami Yogananda', authorImage: 'https://images.pexels.com/photos/3785081/pexels-photo-3785081.jpeg?auto=compress&cs=tinysrgb&w=100',
    date: 'June 23, 2026', readTime: 10, tags: ['om', 'mantra', 'meditation', 'spirituality'],
    featured: false, trending: false,
  },
];

export const dreamPosts: Article[] = [
  { id: 'd1', slug: 'dream-about-cow-meaning', title: 'Dream About Cow', excerpt: 'Spiritual and cultural meaning of seeing a cow in your dream.', category: 'Dream Meanings', image: 'https://images.pexels.com/photos/735968/pexels-photo-735968.jpeg?auto=compress&cs=tinysrgb&w=400', author: 'Dr. Priya Sharma', date: 'July 4, 2026', readTime: 8, tags: ['cow', 'animals'], luckyNumber: 7, luckyColor: 'Green' },
  { id: 'd2', slug: 'dream-about-snake-meaning', title: 'Dream About Snake', excerpt: 'Snake dreams and their deeper spiritual significance.', category: 'Dream Meanings', image: 'https://images.pexels.com/photos/2062316/pexels-photo-2062316.jpeg?auto=compress&cs=tinysrgb&w=400', author: 'Dr. Priya Sharma', date: 'June 30, 2026', readTime: 9, tags: ['snake', 'animals'], luckyNumber: 3, luckyColor: 'Blue' },
  { id: 'd3', slug: 'dream-about-water-meaning', title: 'Dream About Water', excerpt: 'Water symbolism in dreams across different cultures.', category: 'Dream Meanings', image: 'https://images.pexels.com/photos/1028741/pexels-photo-1028741.jpeg?auto=compress&cs=tinysrgb&w=400', author: 'Dr. Priya Sharma', date: 'June 25, 2026', readTime: 7, tags: ['water', 'elements'], luckyNumber: 9, luckyColor: 'White' },
  { id: 'd4', slug: 'dream-about-flying-meaning', title: 'Dream About Flying', excerpt: 'Flying dreams indicate freedom, ambition, and spiritual elevation.', category: 'Dream Meanings', image: 'https://images.pexels.com/photos/3155666/pexels-photo-3155666.jpeg?auto=compress&cs=tinysrgb&w=400', author: 'Dr. Priya Sharma', date: 'June 20, 2026', readTime: 6, tags: ['flying', 'freedom'], luckyNumber: 1, luckyColor: 'Yellow' },
  { id: 'd5', slug: 'dream-about-gold-meaning', title: 'Dream About Gold', excerpt: 'Gold in dreams often signals prosperity, success, and achievement.', category: 'Dream Meanings', image: 'https://images.pexels.com/photos/1893552/pexels-photo-1893552.jpeg?auto=compress&cs=tinysrgb&w=400', author: 'Dr. Priya Sharma', date: 'June 15, 2026', readTime: 7, tags: ['gold', 'prosperity'], luckyNumber: 8, luckyColor: 'Gold' },
  { id: 'd6', slug: 'dream-about-fire-meaning', title: 'Dream About Fire', excerpt: 'Fire dreams symbolize transformation, passion, and purification.', category: 'Dream Meanings', image: 'https://images.pexels.com/photos/266526/pexels-photo-266526.jpeg?auto=compress&cs=tinysrgb&w=400', author: 'Dr. Priya Sharma', date: 'June 10, 2026', readTime: 8, tags: ['fire', 'transformation'], luckyNumber: 5, luckyColor: 'Red' },
  { id: 'd7', slug: 'dream-about-baby-meaning', title: 'Dream About Baby', excerpt: 'Babies in dreams represent new beginnings, potential, and purity.', category: 'Dream Meanings', image: 'https://images.pexels.com/photos/35537/child-children-girl-happy.jpg?auto=compress&cs=tinysrgb&w=400', author: 'Dr. Priya Sharma', date: 'June 5, 2026', readTime: 7, tags: ['baby', 'new beginnings'], luckyNumber: 6, luckyColor: 'Pink' },
  { id: 'd8', slug: 'dream-about-teeth-falling-meaning', title: 'Dream About Teeth Falling', excerpt: 'One of the most common dreams — what losing teeth really signals.', category: 'Dream Meanings', image: 'https://images.pexels.com/photos/1519088/pexels-photo-1519088.jpeg?auto=compress&cs=tinysrgb&w=400', author: 'Dr. Priya Sharma', date: 'June 1, 2026', readTime: 8, tags: ['teeth', 'anxiety'], luckyNumber: 2, luckyColor: 'White' },
  { id: 'd9', slug: 'dream-about-dead-person-meaning', title: 'Dream About Dead Person', excerpt: 'When deceased loved ones appear in dreams — spiritual interpretations.', category: 'Dream Meanings', image: 'https://images.pexels.com/photos/1028741/pexels-photo-1028741.jpeg?auto=compress&cs=tinysrgb&w=400', author: 'Dr. Priya Sharma', date: 'May 28, 2026', readTime: 10, tags: ['death', 'ancestors'], luckyNumber: 4, luckyColor: 'White' },
  { id: 'd10', slug: 'dream-about-rain-meaning', title: 'Dream About Rain', excerpt: 'Rain dreams can mean cleansing, abundance, or emotional release.', category: 'Dream Meanings', image: 'https://images.pexels.com/photos/125510/pexels-photo-125510.jpeg?auto=compress&cs=tinysrgb&w=400', author: 'Dr. Priya Sharma', date: 'May 25, 2026', readTime: 6, tags: ['rain', 'nature'], luckyNumber: 9, luckyColor: 'Blue' },
  { id: 'd11', slug: 'dream-about-lion-meaning', title: 'Dream About Lion', excerpt: 'The lion in your dream represents courage, authority, and power.', category: 'Dream Meanings', image: 'https://images.pexels.com/photos/247502/pexels-photo-247502.jpeg?auto=compress&cs=tinysrgb&w=400', author: 'Dr. Priya Sharma', date: 'May 20, 2026', readTime: 8, tags: ['lion', 'animals', 'power'], luckyNumber: 1, luckyColor: 'Orange' },
  { id: 'd12', slug: 'dream-about-elephant-meaning', title: 'Dream About Elephant', excerpt: 'Elephants symbolize wisdom, strength, loyalty, and good fortune.', category: 'Dream Meanings', image: 'https://images.pexels.com/photos/631317/pexels-photo-631317.jpeg?auto=compress&cs=tinysrgb&w=400', author: 'Dr. Priya Sharma', date: 'May 15, 2026', readTime: 9, tags: ['elephant', 'animals', 'wisdom'], luckyNumber: 8, luckyColor: 'Grey' },
  { id: 'd13', slug: 'dream-about-marriage-meaning', title: 'Dream About Marriage', excerpt: 'Marriage dreams reflect union, commitment, or major life transitions.', category: 'Dream Meanings', image: 'https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg?auto=compress&cs=tinysrgb&w=400', author: 'Dr. Priya Sharma', date: 'May 10, 2026', readTime: 7, tags: ['marriage', 'relationships'], luckyNumber: 6, luckyColor: 'Red' },
  { id: 'd14', slug: 'dream-about-house-meaning', title: 'Dream About House', excerpt: 'Houses in dreams represent the self — each room reflects an aspect of your psyche.', category: 'Dream Meanings', image: 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=400', author: 'Dr. Priya Sharma', date: 'May 5, 2026', readTime: 8, tags: ['house', 'self', 'psyche'], luckyNumber: 4, luckyColor: 'Brown' },
  { id: 'd15', slug: 'dream-about-money-meaning', title: 'Dream About Money', excerpt: 'Money dreams often reflect your feelings about power, security, and self-worth.', category: 'Dream Meanings', image: 'https://images.pexels.com/photos/1694847/pexels-photo-1694847.jpeg?auto=compress&cs=tinysrgb&w=400', author: 'Dr. Priya Sharma', date: 'April 30, 2026', readTime: 7, tags: ['money', 'wealth', 'power'], luckyNumber: 8, luckyColor: 'Green' },
  { id: 'd16', slug: 'dream-about-dog-meaning', title: 'Dream About Dog', excerpt: 'Dogs in dreams symbolize loyalty, friendship, and protection.', category: 'Dream Meanings', image: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=400', author: 'Dr. Priya Sharma', date: 'April 25, 2026', readTime: 7, tags: ['dog', 'animals', 'loyalty'], luckyNumber: 3, luckyColor: 'Brown' },
  { id: 'd17', slug: 'dream-about-fish-meaning', title: 'Dream About Fish', excerpt: 'Fish are symbols of abundance, subconscious mind, and spiritual insight.', category: 'Dream Meanings', image: 'https://images.pexels.com/photos/128756/pexels-photo-128756.jpeg?auto=compress&cs=tinysrgb&w=400', author: 'Dr. Priya Sharma', date: 'April 20, 2026', readTime: 8, tags: ['fish', 'animals', 'abundance'], luckyNumber: 7, luckyColor: 'Blue' },
  { id: 'd18', slug: 'dream-about-black-cat-meaning', title: 'Dream About Black Cat', excerpt: 'Black cats carry deep cultural symbolism — good luck or bad omen?', category: 'Dream Meanings', image: 'https://images.pexels.com/photos/2071873/pexels-photo-2071873.jpeg?auto=compress&cs=tinysrgb&w=400', author: 'Dr. Priya Sharma', date: 'April 15, 2026', readTime: 7, tags: ['cat', 'animals', 'mystery'], luckyNumber: 13, luckyColor: 'Black' },
  { id: 'd19', slug: 'dream-about-spider-meaning', title: 'Dream About Spider', excerpt: 'Spider dreams weave together themes of creativity, fate, and feminine energy.', category: 'Dream Meanings', image: 'https://images.pexels.com/photos/37833/rainbow-lorikeet-parrots-australia-rainbow-37833.jpeg?auto=compress&cs=tinysrgb&w=400', author: 'Dr. Priya Sharma', date: 'April 10, 2026', readTime: 8, tags: ['spider', 'creativity', 'fate'], luckyNumber: 8, luckyColor: 'Purple' },
  { id: 'd20', slug: 'dream-about-exam-meaning', title: 'Dream About Failing Exam', excerpt: 'Exam failure dreams are incredibly common — here\'s what your mind is processing.', category: 'Dream Meanings', image: 'https://images.pexels.com/photos/1056251/pexels-photo-1056251.jpeg?auto=compress&cs=tinysrgb&w=400', author: 'Dr. Priya Sharma', date: 'April 5, 2026', readTime: 6, tags: ['exam', 'anxiety', 'performance'], luckyNumber: 2, luckyColor: 'Blue' },
];

export const products: Product[] = [
  {
    id: 'p1', slug: 'ashwagandha-root-powder',
    name: 'Organic Ashwagandha Root Powder', price: 599, originalPrice: 799,
    image: 'https://images.pexels.com/photos/6693663/pexels-photo-6693663.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Supplements', rating: 4.8, reviews: 234, badge: 'SALE', discount: 25,
    description: 'Pure organic ashwagandha root powder, KSM-66 standardized extract. Helps reduce stress, improve sleep, and boost immunity.',
    tags: ['adaptogen', 'stress', 'immunity'], inStock: true,
  },
  {
    id: 'p2', slug: 'cold-pressed-coconut-oil',
    name: 'Cold Pressed Virgin Coconut Oil', price: 399,
    image: 'https://images.pexels.com/photos/725998/pexels-photo-725998.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Hair Care', rating: 4.6, reviews: 189, badge: 'NEW',
    description: 'Cold-pressed, unrefined virgin coconut oil for hair, skin, and cooking. Rich in lauric acid and medium-chain triglycerides.',
    tags: ['coconut oil', 'hair', 'skin'], inStock: true,
  },
  {
    id: 'p3', slug: 'yoga-mat-premium',
    name: 'Premium Non-Slip Yoga Mat', price: 1299, originalPrice: 1799,
    image: 'https://images.pexels.com/photos/3823488/pexels-photo-3823488.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Yoga Accessories', rating: 4.7, reviews: 156, badge: 'SALE', discount: 28,
    description: '6mm thick premium eco-friendly yoga mat with alignment lines. Superior grip and cushioning for any yoga style.',
    tags: ['yoga', 'exercise', 'fitness'], inStock: true,
  },
  {
    id: 'p4', slug: 'triphala-churna',
    name: 'Triphala Churna – Digestive Support', price: 299,
    image: 'https://images.pexels.com/photos/3735218/pexels-photo-3735218.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Supplements', rating: 4.5, reviews: 312, badge: 'HOT',
    description: 'Traditional Ayurvedic tri-fruit formula. Supports digestion, detoxification, and bowel health naturally.',
    tags: ['triphala', 'digestion', 'detox'], inStock: true,
  },
  {
    id: 'p5', slug: 'rosehip-face-serum',
    name: 'Rosehip & Vitamin C Face Serum', price: 799, originalPrice: 999,
    image: 'https://images.pexels.com/photos/3785147/pexels-photo-3785147.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Skin Care', rating: 4.9, reviews: 428, badge: 'SALE', discount: 20,
    description: 'Potent antioxidant serum with 15% Vitamin C and rosehip oil. Brightens skin, fades dark spots, and boosts collagen.',
    tags: ['face serum', 'vitamin c', 'brightening'], inStock: true,
  },
  {
    id: 'p6', slug: 'organic-shilajit-resin',
    name: 'Pure Himalayan Shilajit Resin', price: 1499,
    image: 'https://images.pexels.com/photos/6693663/pexels-photo-6693663.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Supplements', rating: 4.7, reviews: 98, badge: 'NEW',
    description: 'Authentic Himalayan shilajit resin. High fulvic acid content. Energy, vitality, and cognitive support.',
    tags: ['shilajit', 'energy', 'men health'], inStock: true,
  },
  {
    id: 'p7', slug: 'neem-turmeric-face-pack',
    name: 'Neem & Turmeric Face Pack', price: 349,
    image: 'https://images.pexels.com/photos/3762467/pexels-photo-3762467.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Skin Care', rating: 4.4, reviews: 267, badge: undefined,
    description: 'Purifying face pack with neem, turmeric, and sandalwood. Clears acne, reduces oiliness, and improves skin tone.',
    tags: ['face pack', 'neem', 'acne'], inStock: true,
  },
  {
    id: 'p8', slug: 'meditation-mala-beads',
    name: 'Rudraksha Meditation Mala Beads', price: 899, originalPrice: 1199,
    image: 'https://images.pexels.com/photos/1051838/pexels-photo-1051838.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Spirituality', rating: 4.8, reviews: 142, badge: 'SALE', discount: 25,
    description: '108 authentic Rudraksha beads mala. Used for mantra chanting and meditation. Promotes mental clarity and spiritual growth.',
    tags: ['rudraksha', 'mala', 'meditation', 'prayer'], inStock: true,
  },
  {
    id: 'p9', slug: 'brahmi-hair-oil',
    name: 'Brahmi & Amla Hair Growth Oil', price: 449,
    image: 'https://images.pexels.com/photos/725998/pexels-photo-725998.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Hair Care', rating: 4.6, reviews: 389, badge: undefined,
    description: 'Ayurvedic hair oil with Brahmi, Amla, Bhringraj, and Coconut oil. Reduces hair fall and promotes thick, healthy hair growth.',
    tags: ['hair oil', 'brahmi', 'amla', 'hair fall'], inStock: true,
  },
  {
    id: 'p10', slug: 'organic-ghee',
    name: 'A2 Cow Ghee – Bilona Method', price: 699, originalPrice: 849,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Organic Foods', rating: 4.9, reviews: 521, badge: 'HOT', discount: 18,
    description: 'Traditional bilona method A2 ghee from grass-fed cows. Rich in CLA, vitamins A, D, E, K. Best for cooking and Ayurvedic use.',
    tags: ['ghee', 'a2', 'cooking', 'ayurveda'], inStock: true,
  },
  {
    id: 'p11', slug: 'moringa-powder',
    name: 'Organic Moringa Leaf Powder', price: 349,
    image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Supplements', rating: 4.5, reviews: 178, badge: 'NEW',
    description: 'Pure organic moringa powder — the "miracle tree" superfood. Packed with vitamins, minerals, and antioxidants.',
    tags: ['moringa', 'superfood', 'nutrition'], inStock: true,
  },
  {
    id: 'p12', slug: 'copper-water-bottle',
    name: 'Pure Copper Water Bottle 1L', price: 549,
    image: 'https://images.pexels.com/photos/1028741/pexels-photo-1028741.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Wellness', rating: 4.7, reviews: 213, badge: undefined,
    description: 'Pure copper bottle for water storage. Ayurveda recommends drinking copper-infused water for immunity and digestion.',
    tags: ['copper', 'water bottle', 'ayurveda', 'wellness'], inStock: true,
  },
];

export const trendingSearches = [
  'Dream about cow', 'Ashwagandha benefits', 'Yoga for back pain',
  'Dark circles remedy', 'Giloy immunity', 'Weight loss yoga',
  'Dream about snake', 'Turmeric milk benefits',
];

export const healthSubcategories = [
  { name: 'Weight Loss', slug: 'weight-loss', icon: '⚖️', count: 45 },
  { name: 'Diabetes Diet', slug: 'diabetes-diet', icon: '🩺', count: 38 },
  { name: 'Joint Pain', slug: 'joint-pain', icon: '🦴', count: 29 },
  { name: 'Blood Pressure', slug: 'blood-pressure', icon: '❤️', count: 32 },
  { name: 'Sleep Improvement', slug: 'sleep', icon: '💤', count: 24 },
  { name: 'Digestion', slug: 'digestion', icon: '🫁', count: 41 },
  { name: 'Hair Fall', slug: 'hair-fall', icon: '💆', count: 36 },
  { name: 'Stress & Anxiety', slug: 'stress', icon: '🧠', count: 28 },
  { name: 'Immunity', slug: 'immunity', icon: '🛡️', count: 33 },
];

export const ayurvedaHerbs = [
  { name: 'Ashwagandha', slug: 'ashwagandha', image: 'https://images.pexels.com/photos/6693663/pexels-photo-6693663.jpeg?auto=compress&cs=tinysrgb&w=400', benefit: 'Stress & Vitality' },
  { name: 'Shilajit', slug: 'shilajit', image: 'https://images.pexels.com/photos/3735218/pexels-photo-3735218.jpeg?auto=compress&cs=tinysrgb&w=400', benefit: 'Energy & Strength' },
  { name: 'Triphala', slug: 'triphala', image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=400', benefit: 'Digestion & Detox' },
  { name: 'Neem', slug: 'neem', image: 'https://images.pexels.com/photos/3735218/pexels-photo-3735218.jpeg?auto=compress&cs=tinysrgb&w=400', benefit: 'Skin & Blood' },
  { name: 'Amla', slug: 'amla', image: 'https://images.pexels.com/photos/6693663/pexels-photo-6693663.jpeg?auto=compress&cs=tinysrgb&w=400', benefit: 'Vitamin C & Hair' },
  { name: 'Giloy', slug: 'giloy', image: 'https://images.pexels.com/photos/3735218/pexels-photo-3735218.jpeg?auto=compress&cs=tinysrgb&w=400', benefit: 'Immunity Booster' },
  { name: 'Brahmi', slug: 'brahmi', image: 'https://images.pexels.com/photos/6693663/pexels-photo-6693663.jpeg?auto=compress&cs=tinysrgb&w=400', benefit: 'Brain & Memory' },
  { name: 'Turmeric', slug: 'turmeric', image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=400', benefit: 'Anti-inflammatory' },
];
